"""Add auth models, multitenancy

Revision ID: 3a48c745ccc7
Revises: d8c793cbfcb5
Create Date: 2026-07-10 15:39:14.571378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a48c745ccc7'
down_revision: Union[str, Sequence[str], None] = 'd8c793cbfcb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_environment_id'), 'environments', ['environment_id'], unique=False)
    op.create_index(op.f('ix_environments_id'), 'environments', ['id'], unique=False)
    op.create_index(op.f('ix_environments_tenant_id'), 'environments', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sso_domain', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('environment_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_environment_id'), 'tenants', ['environment_id'], unique=False)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_tenants_tenant_id'), 'tenants', ['tenant_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('environment_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_environment_id'), 'api_keys', ['environment_id'], unique=False)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('user_identities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('profile_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('environment_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_identities_environment_id'), 'user_identities', ['environment_id'], unique=False)
    op.create_index(op.f('ix_user_identities_id'), 'user_identities', ['id'], unique=False)
    op.create_index(op.f('ix_user_identities_provider_id'), 'user_identities', ['provider_id'], unique=False)
    op.create_index(op.f('ix_user_identities_tenant_id'), 'user_identities', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_identities_user_id'), 'user_identities', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('environment_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_environment_id'), 'user_sessions', ['environment_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_tenant_id'), 'user_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_agent_outputs_incident_id'), 'agent_outputs', ['incident_id'], unique=False)
    op.add_column('audit_logs', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('audit_logs', sa.Column('tenant_id', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('environment_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_audit_logs_environment_id'), 'audit_logs', ['environment_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.add_column('incident_logs', sa.Column('tenant_id', sa.String(), nullable=True))
    op.add_column('incident_logs', sa.Column('environment_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_incident_logs_environment_id'), 'incident_logs', ['environment_id'], unique=False)
    op.create_index(op.f('ix_incident_logs_incident_id'), 'incident_logs', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_logs_tenant_id'), 'incident_logs', ['tenant_id'], unique=False)
    op.add_column('incidents', sa.Column('tenant_id', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('environment_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_incidents_assigned_to'), 'incidents', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_incidents_created_by'), 'incidents', ['created_by'], unique=False)
    op.create_index(op.f('ix_incidents_environment_id'), 'incidents', ['environment_id'], unique=False)
    op.create_index(op.f('ix_incidents_tenant_id'), 'incidents', ['tenant_id'], unique=False)
    op.add_column('reports', sa.Column('tenant_id', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('environment_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_reports_environment_id'), 'reports', ['environment_id'], unique=False)
    op.create_index(op.f('ix_reports_incident_id'), 'reports', ['incident_id'], unique=False)
    op.create_index(op.f('ix_reports_tenant_id'), 'reports', ['tenant_id'], unique=False)
    op.add_column('settings', sa.Column('tenant_id', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('environment_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('settings_user_id_key'), 'settings', type_='unique')
    op.create_index(op.f('ix_settings_environment_id'), 'settings', ['environment_id'], unique=False)
    op.create_index(op.f('ix_settings_tenant_id'), 'settings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_settings_user_id'), 'settings', ['user_id'], unique=True)
    op.add_column('users', sa.Column('tenant_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('environment_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_environment_id'), 'users', ['environment_id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_environment_id'), table_name='users')
    op.drop_column('users', 'environment_id')
    op.drop_column('users', 'tenant_id')
    op.drop_index(op.f('ix_settings_user_id'), table_name='settings')
    op.drop_index(op.f('ix_settings_tenant_id'), table_name='settings')
    op.drop_index(op.f('ix_settings_environment_id'), table_name='settings')
    op.create_unique_constraint(op.f('settings_user_id_key'), 'settings', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('settings', 'environment_id')
    op.drop_column('settings', 'tenant_id')
    op.drop_index(op.f('ix_reports_tenant_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_incident_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_environment_id'), table_name='reports')
    op.drop_column('reports', 'environment_id')
    op.drop_column('reports', 'tenant_id')
    op.drop_index(op.f('ix_incidents_tenant_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_environment_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_by'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_assigned_to'), table_name='incidents')
    op.drop_column('incidents', 'environment_id')
    op.drop_column('incidents', 'tenant_id')
    op.drop_index(op.f('ix_incident_logs_tenant_id'), table_name='incident_logs')
    op.drop_index(op.f('ix_incident_logs_incident_id'), table_name='incident_logs')
    op.drop_index(op.f('ix_incident_logs_environment_id'), table_name='incident_logs')
    op.drop_column('incident_logs', 'environment_id')
    op.drop_column('incident_logs', 'tenant_id')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_environment_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'environment_id')
    op.drop_column('audit_logs', 'tenant_id')
    op.drop_column('audit_logs', 'version')
    op.drop_index(op.f('ix_agent_outputs_incident_id'), table_name='agent_outputs')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_tenant_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_environment_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_identities_user_id'), table_name='user_identities')
    op.drop_index(op.f('ix_user_identities_tenant_id'), table_name='user_identities')
    op.drop_index(op.f('ix_user_identities_provider_id'), table_name='user_identities')
    op.drop_index(op.f('ix_user_identities_id'), table_name='user_identities')
    op.drop_index(op.f('ix_user_identities_environment_id'), table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_environment_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_tenants_tenant_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_environment_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_environments_tenant_id'), table_name='environments')
    op.drop_index(op.f('ix_environments_id'), table_name='environments')
    op.drop_index(op.f('ix_environments_environment_id'), table_name='environments')
    op.drop_table('environments')
    # ### end Alembic commands ###
